<<<<<<< HEAD
# Generated by Django 3.2.20 on 2023-08-28 07:02
=======
# Generated by Django 3.2.20 on 2023-08-28 06:18
>>>>>>> d74014412c3e938a4326b140038530310997af8f

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Name',
            fields=[
                ('name', models.CharField(max_length=80, null=True, verbose_name='Наименование')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'verbose_name': 'Наименование:',
                'verbose_name_plural': 'Наименование:',
=======
            name='ReportDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'star_date',
                'verbose_name_plural': 'end_date',
>>>>>>> d74014412c3e938a4326b140038530310997af8f
            },
        ),
    ]
