# Generated by Django 3.2.20 on 2023-08-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSM',
            fields=[
                ('name', models.CharField(max_length=80, null=True, verbose_name='Наименование')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'verbose_name': 'Наименование:',
                'verbose_name_plural': 'Наименование:',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
