# Generated by Django 3.2.20 on 2023-08-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gsm',
            options={'verbose_name': 'АЗС', 'verbose_name_plural': 'АЗС'},
        ),
        migrations.AddField(
            model_name='gsm',
            name='id_realcom',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gsm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]