# Generated by Django 4.2.4 on 2023-08-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_operation_type'),
        ('core', '0006_fueltype'),
    ]

    operations = [
    ]
