# Generated by Django 4.2.4 on 2023-08-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_0005_operation_type_0006_fueltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_realcom', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=20, verbose_name='Вид операции')),
            ],
            options={
                'verbose_name': 'Вид операции',
                'verbose_name_plural': 'Виды операции',
            },
        ),
        migrations.DeleteModel(
            name='Operation_type',
        ),
        migrations.AlterModelOptions(
            name='fueltype',
            options={'verbose_name': 'Вид топлива', 'verbose_name_plural': 'Виды топлива'},
        ),
    ]
