# Generated by Django 4.2.4 on 2023-08-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_map'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='Card',
        ),
    ]
