# Generated by Django 4.2.4 on 2023-08-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_operationtype_delete_operation_type_and_more'),
        ('core', '0010_rename_map_card'),
    ]

    operations = [
    ]
