# Generated by Django 4.2.4 on 2023-09-06 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_gsm_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс до')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс после')),
                ('dose', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Доза')),
                ('price_som', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, сом')),
                ('sum_som', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма, сом')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fueltype')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operationtype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station')),
            ],
            options={
                'verbose_name': 'Операция по карте',
                'verbose_name_plural': 'Операции по карте',
            },
        ),
    ]
