# Generated by Django 4.2.4 on 2023-09-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cardoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardoperation',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
