# Generated by Django 4.2.4 on 2023-09-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_transport_id_realcom_transport_name_realcom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='id_realcom',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
