# Generated by Django 4.2.4 on 2023-09-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_transport_id_realcom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
