# Generated by Django 4.2.4 on 2023-09-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_transport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversname',
            name='id_realcom',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
