# Generated by Django 4.2.4 on 2023-09-22 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_transport_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transport')),
            ],
        ),
    ]
