# Generated by Django 4.2.4 on 2023-09-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_transport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardoperation',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Баланс после'),
        ),
        migrations.AlterField(
            model_name='cardoperation',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Баланс до'),
        ),
        migrations.AlterField(
            model_name='cardoperation',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.card'),
        ),
        migrations.AlterField(
            model_name='cardoperation',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='cardoperation',
            name='dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Доза'),
        ),
        migrations.AlterField(
            model_name='cardoperation',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fueltype'),
        ),
        migrations.AlterField(
            model_name='cardoperation',
            name='operation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.operationtype'),
        ),
        migrations.AlterField(
            model_name='cardoperation',
            name='price_som',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена, сом'),
        ),
        migrations.AlterField(
            model_name='cardoperation',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.station'),
        ),
        migrations.AlterField(
            model_name='cardoperation',
            name='sum_som',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма, сом'),
        ),
    ]
