# Generated by Django 4.2.4 on 2023-09-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_cardoperation_balance_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=20, verbose_name='Наименование ТС')),
                ('period_start', models.DateTimeField(verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(verbose_name='Конец периода')),
                ('fact_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Факт КМ')),
                ('odometer_mileage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Пробег по одометру')),
                ('trip_mileage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Пробег в поездках')),
                ('start_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Остаток на начало')),
                ('start_level', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нач. уровень')),
                ('fueling_gsm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Заправка ГСМ')),
                ('total_refueled', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Всего заправлено')),
                ('actual_fuel_consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Факт Расход топлива (литр)')),
                ('norm_fuel_consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Норма Расход топлива (литр)')),
                ('departure', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Напр.')),
                ('avg_trip_dut_consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ср. расход по ДУТ в поездках')),
                ('actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='По факту')),
                ('fuel_calculation_norm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Калькуляция нормы расхода')),
                ('departure_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Остаток по пут.листу')),
                ('end_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Остаток на конец')),
                ('end_level', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кон. уровень')),
                ('end_mech_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Остаток кон.мех.')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Разница')),
                ('deficiency', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Недостача')),
                ('surplus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Излишек')),
                ('total_fuel_drained', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Всего топлива слито')),
            ],
        ),
    ]
