# Generated by Django 4.2.4 on 2023-09-22 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_deltareport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deltareport',
            name='surplus',
        ),
        migrations.AddField(
            model_name='deltareport',
            name='avg_dut_consumption',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Ср. расход по ДУТ (весь пробег)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deltareport',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='deltareport',
            name='transport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.transport', verbose_name='Транспорт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='deficiency',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Недостача/Излишек'),
        ),
    ]
