# Generated by Django 4.2.4 on 2023-10-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_driversname_id_realcom'),
        ('core', '0022_remove_deltareport_surplus_and_more'),
    ]

    operations = [
    ]
