# Generated by Django 4.2.4 on 2023-10-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20231010_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelsource',
            name='excel_file',
            field=models.FileField(upload_to='excel/2023/10/'),
        ),
    ]
