# Generated by Django 4.2.4 on 2023-10-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_excelsource_excel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='name_realcom',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='transport',
            name='mark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
