# Generated by Django 4.2.4 on 2023-10-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_transport_id_realcom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltareport',
            name='avg_dut_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ср. расход по ДУТ (весь пробег)'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='avg_trip_dut_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ср. расход по ДУТ в поездках'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='end_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Кон. уровень'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='odometer_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Пробег по одометру'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='start_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Нач. уровень'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='total_fuel_drained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Всего топлива слито'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='total_refueled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Всего заправлено'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transport', verbose_name='Объект транспорт'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='trip_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Пробег в поездках'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='vehicle_name',
            field=models.CharField(max_length=20, verbose_name='Наименование ТС (название с файла)'),
        ),
    ]
