# Generated by Django 4.2.4 on 2023-10-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_deltareport_avg_dut_consumption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=10, verbose_name='Месяц')),
                ('year', models.IntegerField(default=2023, verbose_name='Год')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.excelsource')),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.AddField(
            model_name='deltareport',
            name='month_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.monthreport'),
        ),
        migrations.AlterUniqueTogether(
            name='deltareport',
            unique_together={('month_report', 'transport')},
        ),
    ]
