# Generated by Django 4.2.4 on 2023-10-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_monthreport_deltareport_month_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltareport',
            name='departure',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Напр.'),
        ),
    ]
