# Generated by Django 4.2.4 on 2023-10-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_deltareport_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltareport',
            name='end_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Остаток на конец'),
        ),
    ]
