# Generated by Django 4.2.4 on 2023-10-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_deltareport_end_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthreport',
            options={'ordering': ['year', 'month']},
        ),
    ]
