# Generated by Django 4.2.4 on 2023-10-17 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_deltareport_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltareport',
            name='actual_fuel_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Факт Расход топлива (литр)'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='deficiency',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Недостача/Излишек'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='departure_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Остаток по пут.листу'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='end_mech_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Остаток кон.мех.'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='fact_km',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Факт КМ'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='fuel_calculation_norm',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Калькуляция нормы расхода'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='fueling_gsm',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Заправка ГСМ'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='month_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.monthreport'),
        ),
        migrations.AlterField(
            model_name='deltareport',
            name='norm_fuel_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Норма Расход топлива (литр)'),
        ),
    ]
