# Generated by Django 4.2.4 on 2024-07-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_deltareport_start_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelsource',
            name='excel_file',
            field=models.FileField(upload_to='excel/2024/7/'),
        ),
        migrations.AlterField(
            model_name='monthreport',
            name='month',
            field=models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=7, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='monthreport',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Год'),
        ),
    ]
