# Generated by Django 4.2.4 on 2024-07-23 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_excelsource_excel_file_alter_monthreport_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KTGReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('day', models.DateField()),
                ('trip_mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Пробег в поездках')),
                ('dart_spending', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Потрачено по ДАРТ')),
                ('dut_spending', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Потрачено по ДУТ')),
                ('avg_dart_spending', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ср. расход по ДАРТ')),
                ('avg_dut_spending', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ср. расход по ДУТ')),
                ('refilled', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Заправлено')),
                ('leaked', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Слито')),
                ('is_working', models.BooleanField(default=True)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transport')),
            ],
        ),
    ]
